### ISSUE TITLE
CAN_LNAME will not function as an FK

### ISSUE THREAD

**Issue by bumfluff007** [shekiat/csi3450_-s23-random-final-project#1]
CAN_LNAME VARCHAR(256),
FOREIGN KEY (CAN_LNAME) REFERENCES CANDIDATES (CAN_LNAME),

Fails during table setup

$query = "ALTER TABLE JOB_HISTORY
ADD FOREIGN KEY (CAN_LNAME) REFERENCES CANDIDATES (CAN_LNAME)";
mysqli_query($con, $query);

fails when editing FK attributes after table creation

**Comment by shekiat** [comment]
error fixed; can_lname must be referenced as a pk in candidates. since can_lname does not have an int data type, it cannot be a PK.
